-- FlowDesk — estrutura de sustentação no Supabase (PostgreSQL)
-- Espelha os modelos SQLAlchemy de app/models.py.
-- Tipos: JSON->JSONB, DateTime->timestamptz, PK int->identity, Float->double precision.
-- PKs usam "generated by default as identity" para permitir migrar os IDs existentes.
-- Sem RLS: o acesso é feito pelo backend com a credencial de serviço (conexão direta).
-- Idempotente: pode rodar de novo sem erro.

create table if not exists organizations (
    id          bigint generated by default as identity primary key,
    name        varchar(160) not null,
    domain      varchar(160) not null default '',
    created_at  timestamptz  not null default now()
);

create table if not exists users (
    id              bigint generated by default as identity primary key,
    org_id          bigint not null references organizations(id),
    email           varchar(200) not null unique,
    name            varchar(160) not null default '',
    hashed_password varchar(255) not null,
    is_active       boolean not null default true,
    created_at      timestamptz not null default now()
);
create index if not exists ix_users_email on users(email);

create table if not exists project_folders (
    id          bigint generated by default as identity primary key,
    org_id      bigint not null references organizations(id),
    name        varchar(160) not null,
    created_at  timestamptz not null default now()
);

create table if not exists projects (
    id                 bigint generated by default as identity primary key,
    org_id             bigint not null references organizations(id),
    folder_id          bigint references project_folders(id),
    name               varchar(160) not null,
    subdomain          varchar(120) not null unique,
    description        text not null default '',
    status             varchar(20) not null default 'draft',
    output_folder_name varchar(80) not null default 'output',
    access_mode        varchar(20) not null default 'whitelist',
    allowed_domain     varchar(160) not null default '',
    -- rascunho do assistente (feature wizard); incluído para compatibilidade futura
    wizard_state       jsonb not null default '{}'::jsonb,
    wizard_dirty       boolean not null default false,
    created_at         timestamptz not null default now(),
    updated_at         timestamptz not null default now()
);

create table if not exists stages (
    id              bigint generated by default as identity primary key,
    project_id      bigint not null references projects(id),
    type            varchar(20) not null,
    name            varchar(160) not null,
    key             varchar(120) not null,
    config          jsonb not null default '{}'::jsonb,
    entry_file      varchar(255) not null default '',
    timeout_seconds integer not null default 120,
    pos_x           double precision not null default 0,
    pos_y           double precision not null default 0,
    created_at      timestamptz not null default now(),
    constraint uq_stage_key unique (project_id, key)
);
create index if not exists ix_stage_project on stages(project_id);

create table if not exists edges (
    id              bigint generated by default as identity primary key,
    project_id      bigint not null references projects(id),
    source_stage_id bigint not null references stages(id),
    target_stage_id bigint not null references stages(id),
    variable_label  varchar(120) not null default ''
);
create index if not exists ix_edge_project on edges(project_id);

create table if not exists source_files (
    id          bigint generated by default as identity primary key,
    project_id  bigint not null references projects(id),
    path        varchar(255) not null,
    content     text not null default '',
    is_dir      boolean not null default false,
    updated_at  timestamptz not null default now(),
    constraint uq_file_path unique (project_id, path)
);
create index if not exists ix_srcfile_project on source_files(project_id);

create table if not exists builds (
    id                bigint generated by default as identity primary key,
    project_id        bigint not null references projects(id),
    hash              varchar(8) not null,
    framework_version varchar(40) not null default '1.0.0',
    status            varchar(20) not null default 'inactive',
    snapshot          jsonb not null default '{}'::jsonb,
    created_at        timestamptz not null default now()
);
create index if not exists ix_build_hash on builds(hash);

create table if not exists executions (
    id          varchar(36) primary key,
    project_id  bigint not null references projects(id),
    stage_id    bigint not null references stages(id),
    build_id    bigint references builds(id),
    stage_name  varchar(160) not null default '',
    stage_type  varchar(20) not null default '',
    status      varchar(20) not null default 'queued',
    stdout      text not null default '',
    stderr      text not null default '',
    input_data  jsonb not null default '{}'::jsonb,
    output_data jsonb not null default '{}'::jsonb,
    run_dir     varchar(255) not null default '',
    started_at  timestamptz not null default now(),
    finished_at timestamptz
);
create index if not exists ix_exec_project_started on executions(project_id, started_at);
create index if not exists ix_exec_stage on executions(stage_id);

create table if not exists roles (
    id          bigint generated by default as identity primary key,
    project_id  bigint not null references projects(id),
    name        varchar(80) not null,
    description varchar(255) not null default ''
);

create table if not exists project_members (
    id          bigint generated by default as identity primary key,
    project_id  bigint not null references projects(id),
    email       varchar(200) not null,
    roles       jsonb not null default '[]'::jsonb,
    constraint uq_member_email unique (project_id, email)
);

create table if not exists env_vars (
    id          bigint generated by default as identity primary key,
    project_id  bigint not null references projects(id),
    key         varchar(120) not null,
    value       text not null default '',
    secret      boolean not null default true,
    constraint uq_env_key unique (project_id, key)
);

create table if not exists api_keys (
    id          bigint generated by default as identity primary key,
    project_id  bigint not null references projects(id),
    name        varchar(120) not null,
    token       varchar(80) not null,
    created_at  timestamptz not null default now()
);
create index if not exists ix_apikey_token on api_keys(token);

create table if not exists connectors (
    id          bigint generated by default as identity primary key,
    project_id  bigint not null references projects(id),
    type        varchar(40) not null,
    name        varchar(120) not null,
    config      jsonb not null default '{}'::jsonb,
    connected   boolean not null default false
);

create table if not exists data_tables (
    id          bigint generated by default as identity primary key,
    project_id  bigint not null references projects(id),
    name        varchar(120) not null,
    columns     jsonb not null default '[]'::jsonb
);

create table if not exists data_rows (
    id          bigint generated by default as identity primary key,
    table_id    bigint not null references data_tables(id),
    values      jsonb not null default '{}'::jsonb
);

create table if not exists chat_messages (
    id          bigint generated by default as identity primary key,
    project_id  bigint not null references projects(id),
    role        varchar(20) not null,
    content     text not null default '',
    meta        jsonb not null default '{}'::jsonb,
    tokens      integer not null default 0,
    created_at  timestamptz not null default now()
);
create index if not exists ix_chat_project on chat_messages(project_id);

create table if not exists pending_actions (
    id          bigint generated by default as identity primary key,
    project_id  bigint not null references projects(id),
    kind        varchar(40) not null,
    title       varchar(255) not null,
    payload     jsonb not null default '{}'::jsonb,
    status      varchar(20) not null default 'pending',
    created_at  timestamptz not null default now()
);
